In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
l = [1, 2, 3]
l

[1, 2, 3]

In [6]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [10]:
import sys

sys.getsizeof(python_list[0]) * len(python_list)

2800

In [11]:
numpy_array = np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [12]:
numpy_array.nbytes

800

In [ ]:
l1 = [1, 2, 3]
l2 = [8, 7, 9]

print(tuple(zip(l1, l2)))

((1, 8), (2, 7), (3, 9))


In [16]:
import time

size = 1000000

l1 = list(range(size))
l2 = list(range(size))

start_time = time.time()
l3 = [x+y for x , y in zip(l1,l2)]
end_time = time.time()

print("Python list took: ", end_time - start_time)

Python list took:  0.0888674259185791


In [17]:
n1 = np.arange(size)
n2 = np.arange(size)

n1[:4], n2[:4]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [18]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()
print("Numpy array took: ", end_time-start_time)

Numpy array took:  0.006433963775634766


#### Benefit#3: Convenient use with Built In Functions

In [19]:
l1 = list(range(5))
l2 = list(range(6,17))

l3 = [x+y for x , y in zip(l1 , l2)]
l3

[6, 8, 10, 12, 14]

In [23]:
n1 = np.arange(5)
n2 = np.arange(5)
n1, n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [24]:
n1*n2

array([ 0,  1,  4,  9, 16])

In [25]:
n1+n2

array([0, 2, 4, 6, 8])

In [26]:
n1-n2

array([0, 0, 0, 0, 0])