In [1]:
import numpy as np

In [2]:
rev_q1 = np.array([10, 12, 9])
rev_q1.ndim

1

In [3]:
rev = np.array([[10, 12, 9],[15, 11, 13]])
rev.ndim

2

In [4]:
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [6]:
print(rev[1,0])

15


In [7]:
rev[1,0] = 14
rev

array([[10, 12,  9],
       [14, 11, 13]])

In [8]:
rev.dtype

dtype('int64')

In [ ]:
rev = np.array([[10, 12, 9], [15, 11, 13]], dtype = np.float64)

rev.dtype   # float 64 means each of the element is occupying 64 bits in meomory.

dtype('float64')

In [10]:
rev.itemsize # each of the element occupy 8 byte in memory.

8

In [ ]:
rev.size # total number of elements = 6

6

In [12]:
rev.shape

(2, 3)

In [13]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [14]:
np.sort(rev)

array([[ 9., 10., 12.],
       [11., 13., 15.]])

In [15]:
np.sort(rev, axis = None)

array([ 9., 10., 11., 12., 13., 15.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [23]:
np.linspace(10, 20, 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [24]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [25]:
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [26]:
rev.reshape(3, 2)

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [28]:
rev.reshape(6,1)

array([[10.],
       [12.],
       [ 9.],
       [15.],
       [11.],
       [13.]])

In [29]:
rev.min()

np.float64(9.0)

In [30]:
rev.max()

np.float64(15.0)

In [31]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [33]:
rev.sum(axis = 1) # horizontal sum

array([31., 39.])

In [34]:
rev.sum(axis = 0) # vertical sum

array([25., 23., 22.])

In [35]:
b = np.array([1,4,16])

In [36]:
np.sqrt(b)

array([1., 2., 4.])