In [ ]:
import numpy as np
# Sales data for Quarter 1 (Matrix1)
# Rows represent different products in quantities, columns represent different regions.

q1 = np.array([
    [200, 220, 250], # Product A
    [150, 180, 210], # Product B
    [300, 330, 360]  # Product C
])


q2 = np.array([
    [209, 231, 259], # Product A
    [155, 192, 222], # Product B
    [310, 340, 375]  # Product C
])

In [2]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [3]:
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [5]:
((q2-q1)/q1)*100

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [6]:
q1

array([[200, 220, 250],
       [150, 180, 210],
       [300, 330, 360]])

In [ ]:
prices = np.array([
    [10, 12, 11], # prices for Product A in different regions
    [8, 9, 10],   # prices for Product B in different regions
    [15, 16, 17]  # prices for Product C in different regions
])

q1_revenue = q1 * prices
q1_revenue # total revenue for q1 in different countries

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [10]:
# Discount
q1_discounts = q1_revenue * 0.2
q1_discounts

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [12]:
net_revenue = q1_revenue - q1_discounts
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [14]:
print(np.sum(net_revenue))

22568.0


In [13]:
np.sum(q1_discounts)

np.float64(5642.0)

In [15]:
features = np.array([
    [2000, 3], # house 1
    [1800, 2]  # house 2
])

weights = np.array([150, 50000])

np.dot(features, weights)

array([450000, 370000])

In [16]:
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])

np.cross(c, d)

array([-3,  6, -3])