In [3]:
import numpy as np

In [4]:
a = np.array([6, 7, 8, 9])

In [5]:
a[0:2]

array([6, 7])

In [6]:
a[-2:]

array([8, 9])

In [7]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [8]:
b[1][2]

np.int64(6)

In [9]:
b[2][0]

np.int64(7)

In [10]:
b[-1, 0:2] # last row, first two columns

array([7, 8])

In [11]:
b[: , 1:3]    # give me all the rows and print the last two columns

array([[2, 3],
       [5, 6],
       [8, 9]])

In [12]:
# Customern ID, Name
c = np.array([
    [101, "Mira"],
    [102, "Abdul"],
    [103, "Andrea"]
])

# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08']
])

In [13]:
np.hstack((c, d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08']], dtype='<U32')

In [14]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [15]:
e = np.array([
    [104, "Venkat"],
    [105, "John"],
    [106, "Kathy"],
])

e

array([['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [18]:
np.vstack((c, e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [19]:
transactions = np.array([
    [101, "Mohan", 250.50, '2023-08-01'],
    [102, "Bob", 150.00, '2023-08-02'],
    [103, "Fatima", 300.75, '2023-08-01'],
    [104, "Mohan", 400.20, '2023-08-03'],
    [105, "Aryan", 330.1, '2023-08-04'],
])

a , b = np.hsplit(transactions, [3])

In [20]:
a

array([['101', 'Mohan', '250.5'],
       ['102', 'Bob', '150.0'],
       ['103', 'Fatima', '300.75'],
       ['104', 'Mohan', '400.2'],
       ['105', 'Aryan', '330.1']], dtype='<U32')

In [21]:
b

array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-01'],
       ['2023-08-03'],
       ['2023-08-04']], dtype='<U32')

In [22]:
print(np.hsplit(transactions, [3]))

[array([['101', 'Mohan', '250.5'],
       ['102', 'Bob', '150.0'],
       ['103', 'Fatima', '300.75'],
       ['104', 'Mohan', '400.2'],
       ['105', 'Aryan', '330.1']], dtype='<U32'), array([['2023-08-01'],
       ['2023-08-02'],
       ['2023-08-01'],
       ['2023-08-03'],
       ['2023-08-04']], dtype='<U32')]


In [25]:
x , y = np.vsplit(transactions, [4])

In [26]:
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'Mohan', '400.2', '2023-08-03']], dtype='<U32')

In [27]:
y

array([['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [28]:
monthly_sales = np.array([30, 33, 35, 28, 42])

result = monthly_sales < 32
result

array([ True, False, False,  True, False])

In [29]:
monthly_sales[result]

array([30, 28])

In [32]:
index = np.argmax(monthly_sales)

In [37]:
print(monthly_sales[index])

42


In [38]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'Mohan', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [41]:
t_index = np.argmax(transactions[: , 2].astype(float))
print(t_index)

print(transactions[t_index])

3
['104' 'Mohan' '400.2' '2023-08-03']


In [47]:
x = np.where(transactions[: , 0] == "102")

In [48]:
x

(array([1]),)

In [50]:
print(x[0][0])   # the row no.

1


In [54]:
print(transactions[x[0][0]]) # the whole second row

['102' 'Bob' '150.0' '2023-08-02']


In [55]:
print(transactions[transactions[: , 0] == "102"]) # printing in one line

[['102' 'Bob' '150.0' '2023-08-02']]
